name: Run Daily Script

on:
  schedule:
    - cron: '30 2,17 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  checks: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
          cache: 'pip'

      - name: Cache YDB CLI
        id: ydb-cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.tool_cache }}/ydb
          key: ydb-cli-${{ runner.os }}-${{ hashFiles('**/install_ydb.sh') }}
          restore-keys: setup-python-Linux-x64-24.04-Ubuntu-python-3.11.9-pip-7deccac768bd0da446f6dfdb4484170def9f2689fe7c8390c54c42fbc0abcaf0

      - name: Install YDB CLI
        if: steps.ydb-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ runner.tool_cache }}/ydb
          curl -sSL https://install.ydb.tech/cli | bash -s -- -d ${{ runner.tool_cache }}/ydb
          echo "${{ runner.tool_cache }}/ydb/bin" >> $GITHUB_PATH

      - name: Add YDB CLI to PATH
        if: steps.ydb-cache.outputs.cache-hit == 'true'
        run: echo "${{ runner.tool_cache }}/ydb/bin" >> $GITHUB_PATH

      - name: Run Script
        env:
          CITIES: "huzhir,sahyurta,harantsi,sarma,kurma,buguldeyka,shida,agaluy,sayansk,slyudyanka,baikalsk,utulik,mangutay,kultuk,baykal,angarsk,savvateevka,leestvyanka,irkutsk,nikola,bolshoe_goloustnoe,granovshchina,hayryuzovka,bolshie_koti,patroni,ust-ilimsk"
          ROOMS_DATA_PATH: "./tables/rooms_data"
          HOTELS_STATISTICS_PATH: "./tables/hotels_statistics"
          DATABASE_FILE: "./databases/af_all_2024.csv"
          CITY_CENTER_AND_SEA_DISTANCES_FILE: "./databases/hotels_city_center_and_sea_distances.csv"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          YDB_ENDPOINT: ${{ secrets.YDB_ENDPOINT }}
          YDB_DATABASE: ${{ secrets.YDB_DATABASE }}
          AUTHORIZED_KEY_PATH: "./authorized_key.json"
          LOG_FILE_PATH: "./logs/logging.log"
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Обновление данных: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
