name: Run Daily Script

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  checks: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'

      - name: Install YDB CLI
        run: |
          curl -sSL https://install.ydb.tech/cli | bash
          echo "$HOME/ydb/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
  
      - name: Run Script
        env:
          CITIES: "huzhir,sahyurta,harantsi,sarma,kurma,buguldeyka,shida,agaluy,sayansk,slyudyanka,baikalsk,utulik,mangutay,kultuk,baykal,angarsk,savvateevka,leestvyanka,irkutsk,nikola,bolshoe_goloustnoe,granovshchina,hayryuzovka,bolshie_koti,patroni,ust-ilimsk"
          ROOMS_DATA_PATH: "./tables/rooms_data"
          HOTELS_STATISTICS_PATH: "./tables/hotels_statistics"
          DATABASE_FILE: "./databases/af_all_2024.csv"
          CITY_CENTER_AND_SEA_DISTANCES_FILE: "./databases/hotels_city_center_and_sea_distances.csv"
          CITY_IDS_FILE: "./databases/hotels_city_name_by_id.json"
          DISTRICTS_FILE_PATH: "./databases/city_districts.json"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          YDB_ENDPOINT: ${{ secrets.YDB_ENDPOINT }}
          YDB_DATABASE: ${{ secrets.YDB_DATABASE }}
          AUTHORIZED_KEY_PATH: "./authorized_key.json"
          LOG_FILE_PATH: "./logs/logging.log"
        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Обновление данных: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin HEAD
