name: Run Daily Script

on:
  schedule:
    - cron: '30 2,17 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/Python/3.11.9
          key: python-3.11.9-${{ runner.os }}-${{ runner.arch }}
          restore-keys: |
            python-3.11.9-${{ runner.os }}-
            python-3.11.9-

      - name: Set up Python
        if: steps.cache-python.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'

      - name: Cache YDB CLI
        id: cache-ydb
        uses: actions/cache@v3
        with:
          path: ${{ runner.tool_cache }}/ydb
          key: ydb-${{ runner.os }}-${{ runner.arch }}-v2.19.0
          restore-keys: |
            ydb-${{ runner.os }}-${{ runner.arch }}-
            ydb-${{ runner.os }}-

      - name: Install YDB CLI
        if: steps.cache-ydb.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${{ runner.tool_cache }}/ydb
          curl -sSL https://install.ydb.tech/cli/2.19.0 | bash -s -- -d ${{ runner.tool_cache }}/ydb
          echo "${{ runner.tool_cache }}/ydb/bin" >> $GITHUB_PATH

      - name: Authenticate with YDB
        run: |
          echo '${{ secrets.AUTHORIZED_KEY_JSON }}' > authorized_key.json
          sudo apt-get update && sudo apt-get install -y jq
          export IAM_TOKEN=$(curl -s -d "@authorized_key.json" "https://iam.api.cloud.yandex.net/iam/v1/tokens" | jq -r .iamToken)
          echo "IAM_TOKEN=${IAM_TOKEN}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        env:
          CITIES: "huzhir,sahyurta,harantsi,sarma,kurma,buguldeyka,shida,agaluy,sayansk,slyudyanka,baikalsk,utulik,mangutay,kultuk,baykal,angarsk,savvateevka,leestvyanka,irkutsk,nikola,bolshoe_goloustnoe,granovshchina,hayryuzovka,bolshie_koti,patroni,ust-ilimsk"
          ROOMS_DATA_PATH: "./tables/rooms_data"
          HOTELS_STATISTICS_PATH: "./tables/hotels_statistics"
          DATABASE_FILE: "./databases/af_all_2024.csv"
          CITY_CENTER_AND_SEA_DISTANCES_FILE: "./databases/hotels_city_center_and_sea_distances.csv"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          YDB_ENDPOINT: ${{ secrets.YDB_ENDPOINT }}
          YDB_DATABASE: ${{ secrets.YDB_DATABASE }}
          AUTHORIZED_KEY_PATH: "./authorized_key.json"
          LOG_FILE_PATH: "./logs/logging.log"
          IAM_TOKEN: ${{ env.IAM_TOKEN }}
        run: python main.py
